# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: local
    hooks:
    -   id: bot_mypy
        name: mypy bot
        language: python
        language_version: "3.12"
        entry: mypy --strict -p bot
        additional_dependencies:
        -   mypy==1.7.1
        -   aiohttp==3.9.0
        -   pydantic_settings==2.1.0
        -   Telethon==1.32.1
        -   pydantic==2.5.1
        pass_filenames: false
        always_run: true

    -   id: solver_mypy
        name: mypy solver
        language: python
        language_version: "3.12"
        entry: mypy --strict -p solver
        additional_dependencies:
        -   mypy==1.7.1
        -   aiohttp==3.9.0
        -   pydantic_settings==2.1.0
        -   openai==1.3.6
        -   pytest==7.4.3
        -   pytest-asyncio==0.23.2
        -   pydantic==2.5.1
        -   fastapi==0.105.0
        -   python-multipart==0.0.6
        pass_filenames: false
        always_run: true
