version: '3.8'

services:
    bot:
        restart: always
        build:
            context: ./
            dockerfile: bot/Dockerfile-dev
        env_file:
            - env/bot.env
        volumes:
            - telethon-sessions:/bot/sessions
            - ./:/bot
        depends_on:
            - solver

    solver:
        restart: always
        ports:
            - "80:80"
        build:
            context: ./
            dockerfile: solver/Dockerfile-dev
        env_file:
            - env/mathpix.env
            - env/wolfram.env
            - env/openai.env
        volumes:
            - ./:/solver
volumes:
    telethon-sessions:
