version: '3.8'

services:
    bot:
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        env_file:
            - env/bot.env
            - env/wolfram.env
            - env/mathpix.env
            - env/openai.env
        volumes:
            - telethon-sessions:/bot/sessions
volumes:
    telethon-sessions:
